



all:Compila

Compila:
	@cd Cliente/ ; make
	@cd Servidor/ ; make
clean:
	@cd Cliente; make clean
	@cd Servidor; make clean
ClienteClean:
	@cd Cliente; make clean
CleanControles:
	@cd Cliente; make cleanControles
ServidorClean:
	@cd Servidor;make clean
	
