#!/bin/sh

Home=/home/hgarduno 
DIRPOSTGRESQL=/home/postgres/9.4.6
PATH=$PATH:$Home/SoporteSiscomDesarrollo/Servidor/

DirectorioConfiguracion=$Home/ConfiguracionServiSNTE/Servidor/
ArchivosNomina=$Home/TransferenciasArchivosNomina

LD_LIBRARY_PATH=$Home/SoporteSiscomDesarrollo/Servidor:$DIRPOSTGRESQL/lib:$Home/ServiSNTE/Servidor/


export LD_LIBRARY_PATH 		\
	PATH			\
	DirectorioConfiguracion	\
	ArchivosNomina		\
	DIRPOSTGRESQL

PuertoRN=6345
PuertoAD=6346
start() {
echo "Iniciando el sistema ServiSNTE (Cabeza Juarez)"
su - hgarduno -c "
		export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
		export PATH=$PATH
		export DirectorioConfiguracion=$DirectorioConfiguracion
		export ArchivosNomina=$ArchivosNomina
		export DIRPOSTGRESQL=$DIRPOSTGRESQL
		ServidorSiscom $DirectorioConfiguracion/SiscomServiSNTE$PuertoAD\Ini
		ServidorSiscom $DirectorioConfiguracion/SiscomServiSNTE$PuertoRN\Ini"
echo "Se Inicio de forma correcta el servidor"
}

stop() {
PidReglasNegocio=`cat $DirectorioConfiguracion/ServidorSiscom$PuertoRN\Pid` 
PidAccesoDatos=`cat $DirectorioConfiguracion/ServidorSiscom$PuertoAD\Pid`
if [ $PidAccesoDatos ]
then
echo "Deteniendo el proceso de acceso a datos ($PidAccesoDatos)"
kill -9 $PidAccesoDatos 
fi
if [ $PidReglasNegocio ]
then
echo "Deteniendo el proceso de Reglas del negocio ($PidReglasNegocio)"
kill -9 $PidReglasNegocio
fi

rm $DirectorioConfiguracion/ServidorSiscom$PuertoRN\Pid
rm $DirectorioConfiguracion/ServidorSiscom$PuertoAD\Pid

}

case "$1" in
start)

	start
	;;
stop)
	stop
	;;
esac

