



all:Compila

Compila:
	@cd Cliente ; make
	@cd Cliente; make -f MakefileCliente2
	@cd Servidor ; make
	@cd ServidorProtocolo2;make
clean:
	@cd Cliente; make clean
	@cd Servidor;make clean
	@cd ServidorProtocolo2;make clean
ClienteClean:
	@cd Cliente; make clean

