insert into FormaPagoSat values(0,'01','Efectivo');
insert into FormaPagoSat values(1,'02','Cheque Nominativo');
insert into FormaPagoSat values(2,'03','Transferencia electronica de fondos');
insert into FormaPagoSat values(3,'04','Tarjeta de credito');
insert into FormaPagoSat values(4,'05','Monedero electronica');
insert into FormaPagoSat values(5,'06','Dinero electronico');
insert into FormaPagoSat values(6,'08','Vales de despensa');
insert into FormaPagoSat values(7,'12','Dacion en pago');
insert into FormaPagoSat values(8,'13','Pago por subrogacion');
insert into FormaPagoSat values(9,'14','Pago por consignacion');
insert into FormaPagoSat values(10,'15','Condonacion');
insert into FormaPagoSat values(11,'17','Compensacion');
insert into FormaPagoSat values(12,'23','Novacion');
insert into FormaPagoSat values(13,'24','Confusion');
insert into FormaPagoSat values(14,'25','Remision de deuda');
insert into FormaPagoSat values(15,'26','Prescripcion o caducida');
insert into FormaPagoSat values(16,'27','A satisfaccion del acredo');
insert into FormaPagoSat values(17,'28','Tarjeta de debito');
insert into FormaPagoSat values(18,'29','Tarjeta de servicio');
insert into FormaPagoSat values(19,'30','Aplicacion de anticipo');
insert into FormaPagoSat values(20,'31','Intermediario pagos');
insert into FormaPagoSat values(21,'99','Por definir');

insert into UsoFacturaSat values(0,'G01','Adquisicióe mercancias');
insert into UsoFacturaSat values(1,'G02','Devoluciones, descuentos o bonificaciones');
insert into UsoFacturaSat values(2,'G03','Gastos en general');
insert into UsoFacturaSat values(3,'I01','Construcciones');
insert into UsoFacturaSat values(4,'I02','Mobilario y equipo de oficina por inversiones');
insert into UsoFacturaSat values(5,'I03','Equipo de transporte');
insert into UsoFacturaSat values(6,'I04','Equipo de computo y accesorios');
insert into UsoFacturaSat values(7,'I05','Dados, troqueles, moldes, matrices y herramental');
insert into UsoFacturaSat values(8,'I06','Comunicaciones telefóas');
insert into UsoFacturaSat values(9,'I07','Comunicaciones satelitales');
insert into UsoFacturaSat values(10,'I08','Otra maquinaria y equipo');
insert into UsoFacturaSat values(11,'D01','Honorarios mécos, dentales y gastos hospitalarios.');
insert into UsoFacturaSat values(12,'D02','Gastos mécos por incapacidad o discapacidad');
insert into UsoFacturaSat values(13,'D03','Gastos funerales.');
insert into UsoFacturaSat values(14,'D04','Donativos.');
insert into UsoFacturaSat values(15,'D05','Intereses reales efectivamente pagados por crétos hipotecarios (casa habitación)');
insert into UsoFacturaSat values(16,'D06','Aportaciones voluntarias al SAR.');
insert into UsoFacturaSat values(17,'D07','Primas por seguros de gastos mécos.');
insert into UsoFacturaSat values(18,'D08','Gastos de transportacióscolar obligatoria.');
insert into UsoFacturaSat values(19,'D09','Depóos en cuentas para el ahorro, primas que tengan como base planes de pensiones.');
insert into UsoFacturaSat values(20,'D10','Pagos por servicios educativos (colegiaturas)');
insert into UsoFacturaSat values(21,'P01','Por definir');

insert into MetodoPagoSat values(0,'PUE','Una sola exhibicion');
insert into MetodoPagoSat values(1,'PPD','Parcialidades');
