insert into RegimenFiscal(Regimen,Descripcion) values(601, 'General de Ley Personas Morales');
insert into RegimenFiscal(Regimen,Descripcion) values(603, 'Personas Morales con Fines no Lucrativos');
insert into RegimenFiscal(Regimen,Descripcion) values(605, 'Sueldos y Salarios e Ingresos Asimilados a Salarios');
insert into RegimenFiscal(Regimen,Descripcion) values(606, 'Arrendamiento');
insert into RegimenFiscal(Regimen,Descripcion) values(607, 'Régimen de Enajenación o Adquisición de Bienes');
insert into RegimenFiscal(Regimen,Descripcion) values(608, 'Demás ingresos');
insert into RegimenFiscal(Regimen,Descripcion) values(610, 'Residentes en el Extranjero sin Establecimiento Permanente en México');
insert into RegimenFiscal(Regimen,Descripcion) values(611, 'Ingresos por Dividendos (socios y accionistas)');
insert into RegimenFiscal(Regimen,Descripcion) values(612, 'Personas Físicas con Actividades Empresariales y Profesionales');
insert into RegimenFiscal(Regimen,Descripcion) values(614, 'Ingresos por intereses');
insert into RegimenFiscal(Regimen,Descripcion) values(615, 'Régimen de los ingresos por obtención de premios');
insert into RegimenFiscal(Regimen,Descripcion) values(616, 'Sin obligaciones fiscales');
insert into RegimenFiscal(Regimen,Descripcion) values(620, 'Sociedades Cooperativas de Producción que optan por diferir sus ingresos');
insert into RegimenFiscal(Regimen,Descripcion) values(621, 'Incorporación Fiscal');
insert into RegimenFiscal(Regimen,Descripcion) values(622, 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras');
insert into RegimenFiscal(Regimen,Descripcion) values(623, 'Opcional para Grupos de Sociedades');
insert into RegimenFiscal(Regimen,Descripcion) values(624, 'Coordinados');
insert into RegimenFiscal(Regimen,Descripcion) values(625, 'Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas');
insert into RegimenFiscal(Regimen,Descripcion) values(626, 'Régimen Simplificado de Confianza');
