#!/bin/bash 

source ~/bin/FuncionesComunesBash 

PATH=$PATH:~/bin


export PATH


CosasQueFaltanExpendios()
{
cat << SQL | psql SiscomElectronica  > /dev/null 2> /dev/null  

insert into expendioabierto select idempresa from expendios ; 

SQL

}        
EliminaBodegas()
{
cat << SQL |psql SiscomElectronica
delete from inventariobodega ;
delete from materialbodega ;
delete from bodegaaexpendio ;
delete from transferenciabodegabodega;
delete from bodegas ;

SQL
}

EliminandoBaseExpendio()
{
  
  dropdb $1

}
EliminandoExpendios()
{
   EliminandoBaseExpendio Expendio_100
   EliminandoBaseExpendio Expendio_200
}
################################################ 
###### Se deben Eliminar las bases de datos 
##### de los expendio, y volver a registrarlo
##### esto debido a que la base de datos pudo cambiar 
#  $1 Nombre_Expendio
#  $2 IdExpendio
#  $3 Puerto Acceso datos Expendio
#  $4 Direccion Ip Matriz
CreaExpendio()
{
CreaExpendios 	-IniciaExpendioNuevo  		\
		-Base SiscomElectronica 	\
		-NmbExpendio $1 		\
		-IdExpendio  $2			\
		-BaseExpendio $1 		\
		-Puerto  $3 			\
		-DirIpMatriz $4 

}
EliminandoExpendios
printf "Preparando ambiente Desarrollo\n"
printf "Restaurando la ultima base\n "

CreaExpendios 	-RestauraBaseDatos 			\
		-Base SiscomElectronica 		\
	      	-UltimoArchivo -Prefijo Zacatenco
	
CreaExpendios -DejaSoloMatriz -Base SiscomElectronica




printf "Creando El Expendio 100\n" 

CreaExpendios -IniciaExpendioNuevo 		\
		-Base SiscomElectronica 	\
		-NmbExpendio Expendio_100 	\
		-IdExpendio 100 		\
		-BaseExpendio Expendio_100 	\
		-Puerto 6546 			\
		-DirIpMatriz 127.0.0.1

printf "Creando el Expendio 200\n" 


CreaExpendios -IniciaExpendioNuevo 		\
		-Base SiscomElectronica 	\
		-NmbExpendio Expendio_200 	\
		-IdExpendio 200 		\
		-BaseExpendio Expendio_200 	\
		-Puerto 7546 			\
		-DirIpMatriz 127.0.0.1



printf "Registrando Expendio_100\n"

CreaExpendios -RegistroExpendio  		\
		-BaseMatriz SiscomElectronica 	\
		-BaseExpendio Expendio_100 	\
		-Expendio Expendio_100 		\
		-IdExpendio 100 		\
		-PuertoAdExpendio 6546 		\
		-DirIpAdExpendio 127.0.0.1


printf "Registrando Expendio_200\n"

CreaExpendios -RegistroExpendio  		\
		-BaseMatriz SiscomElectronica 	\
		-BaseExpendio Expendio_200 	\
		-Expendio Expendio_200 		\
		-IdExpendio 200 		\
		-PuertoAdExpendio 7546 		\
		-DirIpAdExpendio 127.0.0.1



CosasQueFaltanExpendios 
EliminaBodegas 


RegistraBodega -RegistroBodegaMatriz 		\
		-IdBodega 100 			\
		-Nombre Bodega_Expendio_100 	\
		-BaseMatriz SiscomElectronica 	\
		-DirIpExpendio 127.0.0.1 	\
		-IdExpendio 100 		\
		-BaseExpendio Expendio_100 	\
		-Usuario hgarduno

RegistraBodega -RegistroBodegaMatriz 		\
		-IdBodega 200 			\
		-Nombre Bodega_Expendio_200 	\
		-BaseMatriz SiscomElectronica 	\
		-DirIpExpendio 127.0.0.1 	\
		-IdExpendio 200 		\
		-BaseExpendio Expendio_200 	\
		-Usuario hgarduno



#echo 'update ambienteactivotimbrado set idambiente=2' |psql SiscomElectronica
#echo "update ambientesfacturacionphp set binariophp='/usr/bin/php'"|psql SiscomElectronica
