drop table Productos;
drop table Proveedor;
drop table ComunicacionProveedor;
drop table MedioComunicacion;
drop table ContactosProveedor;
drop table Contactos;
drop table Compra;
drop table ProductoYProveedor;
drop table CuentaPorPagar;
drop table FormaDePago;
drop table Inventario;
drop table Venta;
drop table Orden;
drop table Cliente;
drop table DatosComunicacion;
drop table MarcaDispositivo;
drop table Practicas;
drop table Faltantes;
create table Productos(chrCveProducto varchar (50) primary key ,chrDscCorta varchar (90),chrFamilia varchar(50));
--create table Productos(chrCveProducto varchar (50) ,chrDscCorta varchar (90),chrFamilia varchar(50));
create table Proveedor(chrCveProveedor varchar (50) primary key,chrRazonSocial varchar(200),chrDireccion varchar(200));
create table ComunicacionProveedor(chrCveProveedor varchar(50),chrCveMedioCom varchar (10));
create table MedioComunicacion(chrCveMedio varchar (10) Primary key,chrDscMedio varchar(256));
create table ContactosProveedor(chrCveProveedor varchar(50),chrCveContacto varchar (50));
create table Contactos(chrCveContacto varchar (51),chrNmbContacto varchar (50));
create table ProductoYProveedor(chrCveProducto varchar(50),chrCveProveedor varchar (50));
create table Compra(dteFechaCompra datetime,chrCveProducto varchar (50) references Productos,chrCveProveedor varchar (25),intCantidad numeric(10,4),numPrcCompra numeric(10,4),numPrcVenta numeric(10,4),numPrcMayoreo numeric(10,4),chrCveFrmPago varchar (50),chrCveContacto varchar (50));
create table CuentaPorPagar(dteFechaCompra date,chrCveProducto varchar (50),chrCveProveedor varchar (10),dteFechaPago date,numImporte numeric(10,4));
create table FormaDePago(chrCvePago varchar (50),chrDscPago  varchar (256));
create table Inventario(chrCveProducto varchar (50),intExistencia numeric(10,4),intExistenciaMin numeric(10,4)); 
create table Venta(dteFechaVenta datetime,chrCveVenta varchar( 50) ,chrCveProducto varchar(50),intCantidad numeric(10,4),chrCveCliente varchar (50),numPrcUnitario numeric (10,4),numPrcTotal	numeric (10,4));
create table Orden(dteFecha date,intNumOrden integer,chrCveVenta varchar (30));
create table Cliente(chrCveCliente varchar(50),chrNmbCliente varchar(50),chrDirCliente varchar(256));
create table DatosComunicacion(chrCveProveedor varchar (50),chrCveContacto varchar (50),chrCveMedio varchar (50),chrMedio varchar (50));
create table MarcaDispositivo(dteFechaVenta datetime,chrCveVenta varchar(50),chrCveProducto varchar(50),DescripcionMarca varchar(512));
create table Practicas(chrCvePractica varchar(50),chrCveProducto varchar(50));
create table Faltantes(chrCveProducto varchar(50),chrDescripcion varchar(512),dteFechaHoy date);
