#!/bin/bash 

source ~/bin/FuncionesComunesBash 

UltimoArchivoS=""

Directorios="BibliotecasQt3.3.8 	\
	     SoporteSiscomElectronica4	\
	     ConfiguracionSiscomElectronica"

ArchivoConfiguracionInterfaz()
{
DirectorioX=$(ObtenDirInstalacion $*)
NmbArchivoConInterfaz=$DirectorioX/ConfiguracionSiscomElectronica/SiscomElectronica.hgarduno

cat << ScriptConfigInterfaz  > $NmbArchivoConInterfaz 


# Para trabajar con las variables del archivo Ini
# debemos considerar que se tomaran 2 tipos de variables
# 
####  
# Al momento de estar distribuyendo las opciones 
# generales observo que se generaran varias categorias
# con lo que la barra de menu practicamente se llena
# por tal motivo sera necesario encontrar la menear 
# para que se creen sub menus 
# Por ejemplo Administracion Siscom
#   Empleados
#            Registro de Empleados
#            Sueldos Empleados 
#   Clientes 
#   	    
#   	    ....

IconoAplicacion.Icono=IconoAplicacion

MenuPrincipal.QPopupMenuPuntoVenta.Texto=Principal Ventas
MenuPrincipal.QPopupMenuPuntoVenta.Icono=Dibujo.png
#{

	QPopupMenuPuntoVenta.QAModuloVentas.Texto=Modulo Ventas
	QPopupMenuPuntoVenta.QAModuloVentas.Icono=IconoQAModuloVentas
	QPopupMenuPuntoVenta.QAModuloVentas.Modulo=libPantallasSiscomElectronica2009.so
	QPopupMenuPuntoVenta.QAModuloVentas.Funcion=InstanciaModuloVentas

	QPopupMenuPuntoVenta.QAOrdenesRegistradas.Texto=Orgenes Registradas
        QPopupMenuPuntoVenta.QAOrdenesRegistradas.Icono=IconoQAModuloOrgenesRegistradas
        QPopupMenuPuntoVenta.QAOrdenesRegistradas.Modulo=libPantallasSiscomElectronica2009.so
        QPopupMenuPuntoVenta.QAOrdenesRegistradas.Funcion=InstanciaOrdenesRegistradas


#}

MenuPrincipal.QPopupMenuAdministracion.Texto=Administracion SISCOM
MenuPrincipal.QPopupMenuAdministracion.Icono=Dibujito.png




#{




	QPopupMenuAdministracion.QAManejadorProductos4.Texto=Manejador De Productos4
        QPopupMenuAdministracion.QAManejadorProductos4.Icono=Dibujo.png
        QPopupMenuAdministracion.QAManejadorProductos4.Modulo=libPantallasSiscomElectronica2009.so
        QPopupMenuAdministracion.QAManejadorProductos4.Funcion=InstanciaManejadorProductos4



	QPopupMenuAdministracion.QAInventario.Texto=Captura Inventario
	QPopupMenuAdministracion.QAInventario.Icono=Dibujo.png 
	QPopupMenuAdministracion.QAInventario.Modulo=libInventario.so
	QPopupMenuAdministracion.QAInventario.Funcion=InstanciaInventario


	QPopupMenuAdministracion.QAManejadorProductos.Texto=Manejador De Productos
	QPopupMenuAdministracion.QAManejadorProductos.Icono=Dibujo.png 
	QPopupMenuAdministracion.QAManejadorProductos.Modulo=libManejadorProductos.so
	QPopupMenuAdministracion.QAManejadorProductos.Funcion=InstanciaManejadorProductos


	QPopupMenuAdministracion.QAManejadorPrecios.Texto=Manejador de precios
	QPopupMenuAdministracion.QAManejadorPrecios.Icono=Dibujo.png 
	QPopupMenuAdministracion.QAManejadorPrecios.Modulo=libManejadorPrecios.so
	QPopupMenuAdministracion.QAManejadorPrecios.Funcion=InstanciaManejadorPrecios

	QPopupMenuAdministracion.QADevoluciones.Texto=Devoluciones
	QPopupMenuAdministracion.QADevoluciones.Icono=Dibujo.png 
	QPopupMenuAdministracion.QADevoluciones.Modulo=libPantallasSiscomElectronica2009.so
	QPopupMenuAdministracion.QADevoluciones.Funcion=InstanciaDevoluciones


	QPopupMenuAdministracion.QAFacturacion4.Texto=Sistema de Facturacion
	QPopupMenuAdministracion.QAFacturacion4.Icono=Dibujo.png 
	QPopupMenuAdministracion.QAFacturacion4.Modulo=libPantallasSiscomElectronica2009.so
	QPopupMenuAdministracion.QAFacturacion4.Funcion=InstanciaFacturando4


#}

MenuPrincipal.QPopupMenuBodegas.Texto=Bodegas
MenuPrincipal.QPopupMenuBodegas.Icono=Dibujo.png

        QPopupMenuBodegas.QAMaterialBodegaExpendio.Texto=Transfiere Material A Expendio
        QPopupMenuBodegas.QAMaterialBodegaExpendio.Icono=IconoQAMaterialBodegaExpendio
        QPopupMenuBodegas.QAMaterialBodegaExpendio.Modulo=libPantallasSiscomElectronica2009.so
        QPopupMenuBodegas.QAMaterialBodegaExpendio.Funcion=InstanciaMaterialBodegaExpendio

        QPopupMenuBodegas.QAInventarioBodega.Texto=Captura Inventario Bodega
        QPopupMenuBodegas.QAInventarioBodega.Icono=IconoQAInventarioBodega
        QPopupMenuBodegas.QAInventarioBodega.Modulo=libPantallasSiscomElectronica2009.so
        QPopupMenuBodegas.QAInventarioBodega.Funcion=InstanciaInventarioBodega

MenuPrincipal.QPopupMenuTransferencias.Texto=Transferencias
MenuPrincipal.QPopupMenuTransferencias.Icono=Dibujo.png
#{
        QPopupMenuTransferencias.QAHistorialTransferencias.Texto=Historial De Transferencias
        QPopupMenuTransferencias.QAHistorialTransferencias.Icono=IconoQAHistorialTransferencias
        QPopupMenuTransferencias.QAHistorialTransferencias.Modulo=libPantallasSiscomElectronica2009.so
        QPopupMenuTransferencias.QAHistorialTransferencias.Funcion=InstanciaHistorialTransferencias

        QPopupMenuTransferencias.QAMaterialAExpendio.Texto=Material A Expendios
        QPopupMenuTransferencias.QAMaterialAExpendio.Icono=IconoQAMaterialAExpendio
        QPopupMenuTransferencias.QAMaterialAExpendio.Modulo=libMaterialAExpendio.so
        QPopupMenuTransferencias.QAMaterialAExpendio.Funcion=InstanciaMaterialAExpendio



        QPopupMenuTransferencias.QAPedidosExpendios.Texto=Pedidos Expendios
        QPopupMenuTransferencias.QAPedidosExpendios.Icono=IconoQAPedidosExpendios
        QPopupMenuTransferencias.QAPedidosExpendios.Modulo=libPantallasSiscomElectronica2009.so
        QPopupMenuTransferencias.QAPedidosExpendios.Funcion=InstanciaPedidosExpendios

        QPopupMenuTransferencias.QATransferenciaExpendioAExpendio.Texto=Tranfiere Expendio A Expendio
        QPopupMenuTransferencias.QATransferenciaExpendioAExpendio.Icono=IconoTransferenciaExpendioAExpendio
        QPopupMenuTransferencias.QATransferenciaExpendioAExpendio.Modulo=libPantallasSiscomElectronica2009.so
        QPopupMenuTransferencias.QATransferenciaExpendioAExpendio.Funcion=InstanciaTransferenciaExpendioAExpendio


#}

MenuPrincipal.QPopupMenuCompras.Texto=Compras
MenuPrincipal.QPopupMenuCompras.Icono=Dibujo.png
	QPopupMenuCompras.QACompras.Texto=Compras
        QPopupMenuCompras.QACompras.Icono=IconoQACompras
        QPopupMenuCompras.QACompras.Modulo=libCompras.so
        QPopupMenuCompras.QACompras.Funcion=InstanciaCompras

MenuPrincipal.QPopupMenuReportes.Texto=Reportes Ventas
MenuPrincipal.QPopupMenuReportes.Icono=Dibujito.png
	QPopupMenuReportes.QAReporteVentas4.Texto=Reporte De Ventas (4)
        QPopupMenuReportes.QAReporteVentas4.Icono=Dibujo.png 
        QPopupMenuReportes.QAReporteVentas4.Modulo=libPantallasSiscomElectronica2009.so
        QPopupMenuReportes.QAReporteVentas4.Funcion=InstanciaReporteVentas4



DatosExpendios.Zacatenco.Encargado.Comunicacion.Telefono=1
DatosExpendios.Zacatenco.Encargado.Comunicacion.Correo=1
DatosExpendios.Zacatenco.Encargado.Comunicacion.Nextel=1
DatosExpendios.Zacatenco.Comunicaciones.DireccionIp=2
DatosExpendios.Zacatenco.Comunicaciones.Puerto=3




ScriptConfigInterfaz



}
ArchivoComunicacionServidor()
{
DirectorioX=$(ObtenDirInstalacion $*)
NmbArchivoC=$DirectorioX/ConfiguracionSiscomElectronica/SiscomTiendasComunicaciones3.txt
cat << ScriptComunicacion > $NmbArchivoC 
192.168.1.98@5645@Siscom Electronica 

ScriptComunicacion
}
SiscomElectronicaCliente()
{
DirectorioX=$(ObtenDirInstalacion $*)
NmbScriptSiscomCliente=$DirectorioX/ConfiguracionSiscomElectronica/SISCOMTiendas3.Produccion
cat << ScriptSiscomCliente > $NmbScriptSiscomCliente 
#!/bin/sh 

LD_LIBRARY_PATH=$DirectorioX/SiscomElectronica.Liberacion/Cliente
LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$DirectorioX/BibliotecasQt3.3.8
LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$DirectorioX/SoporteSiscomElectronica4

PATH=$DirectorioX/SiscomElectronica.Liberacion/Cliente
DirSistema=$DirectorioX/SiscomElectronica.Liberacion
DirectorioConfiguracion=$DirectorioX/SiscomElectronica.Liberacion/Cliente
ArchivoConfiguracionModulos=$DirectorioX/ConfiguracionSiscomElectronica/SiscomElectronica.hgarduno
Aplicacion=SISCOMElectronica
PtoComSvr2=2645
##RutaIconos=$HOME/.SiscomElectronica/Cliente/Iconos

ArchivoServidores=$DirectorioX/ConfiguracionSiscomElectronica/SiscomTiendasComunicaciones3.txt

IdExpendio=-1165434773
DirIpSvr=127.0.0.1
PtoComSvr=5645
IdCaja=1
UtilizacionVentas=libSiscomVentasUtilizacionInspironPentiumMZacatenco.so
BibliotecaIconos=libIconosSiscomElectronica.so
CpuInfo=CpuInfo

export LD_LIBRARY_PATH
export PATH
export DirectorioConfiguracion
export ArchivoConfiguracionModulos
export Aplicacion
export PtoComSvr2
export RutaIconos
export ArchivoServidores

export IdExpendio
export DirIpSvr
export PtoComSvr
export IdCaja
export DirSistema
export BibliotecaIconos
export UtilizacionVentas
export CpuInfo
export IdExpendio
export TipoAccesoSistema
export ServidoresAccesoSistema

SISCOMTiendas3 Maximizada

ScriptSiscomCliente

chmod oug+x $NmbScriptSiscomCliente
}

CreaDirectorios()
{

for X in $Directorios 
do 
   Directorio=$1/$X
      if [ "$(DirectorioInstalacion $Directorio)" == "0" ]
      then
           mkdir $Directorio
      fi
done

}
DirectorioInstalacion()
{
  if [ -d $1 ]
  then 
  	echo 1
  else 
  	echo 0
  fi
}

CreandoDirectorioInstalacion()
{

if [  "$(DirectorioInstalacion $1)" == "1" ]
then 
  
     rm $(DirectorioInstalacion $1)
 else
     printf "No esta el directorio de instalacion\n"
     mkdir $1
  fi

  CreaDirectorios $*
}
EstaEliminaInstalacion()
{
  OpcionABuscar=Elimina
  echo $(EstaLaOpcion $*)
}

EstaInstalando()
{
  OpcionABuscar=Instalando
  echo $(EstaLaOpcion $*)
}

EstaDirInstalacion()
{
  OpcionABuscar=DirInstalacion 
  echo $(EstaLaOpcion $*)
}
EstaDirIp()
{
OpcionABuscar=DirIp
echo $(EstaLaOpcion $*)
}
EstaUsuario()
{
OpcionABuscar=Usuario
echo $(EstaLaOpcion $*)

}

EstaEnviaInstalacion()
{
 OpcionABuscar=EnviaInstalacion
 echo $(EstaLaOpcion $*)
}
EstaInstalandoQt3()
{
  OpcionABuscar=InstalandoQt3 
  echo $(EstaLaOpcion $*)
}
EstaUsaEsteArchivo()
{
  
  OpcionABuscar=UsaEsteArchivo
  echo $(EstaLaOpcion $*)
}
EstaDirectorioPasando()
{
  OpcionABuscar=DirectorioPasando
  echo $(EstaLaOpcion $*)
}
ObtenDirInstalacion()
{
Parametro=DirInstalacion
echo $(ObtenParametroEntrada $*)
}
EstaOtraOpcion()
{
   echo 1
}
ObtenUsaEsteArchivo()
{
Parametro=UsaEsteArchivo
echo $(ObtenParametroEntrada $*)
}
ObtenDirIp()
{
Parametro=DirIp
echo $(ObtenParametroEntrada $*)
}
ObtenUsuario()
{
Parametro=Usuario
echo $(ObtenParametroEntrada $*)
}

ObtenDirectorioPasando()
{
Parametro=DirectorioPasando
echo $(ObtenParametroEntrada $*)
}

VerificandoParametrosInstalacion()
{
    if [[ "$(EstaDirInstalacion $*)" == "1" &&
         "$(EstaOtraOpcion $*)"     == "1" ]]
    then 
           echo 1
     else
     	   echo 0
    fi
}
ModoUsoInstalacion()
{
printf "Falta algo ....\n"
}
CopiandoQt3()
{
 cp $QTDIR/lib/libqt-mt.so.3.3.8 $DirectorioPasando
 cp $QTDIR/lib/libqui.so.1.0.0 $DirectorioPasando
}
EmpaquetaArchivosQt3()
{
if [ -f $DirectorioPasando/ArchivosQt3.tar.xz ] 
then 
	rm $DirectorioPasando/ArchivosQt3.tar.xz
fi
(cd $DirectorioPasando; \
 tar cf ArchivosQt3.tar libqt-mt.so.3.3.8 libqui.so.1.0.0; \
 xz -z ArchivosQt3.tar)
}
TransfiriendoArchivosQt3()
{
ArchivoATransferir=$DirectorioPasando/ArchivosQt3.tar.xz
ConexionDestino="$(ObtenUsuario $*)@$(ObtenDirIp $*):$(ObtenDirInstalacion $*)"
printf "Enviando scp %s %s\n" $ArchivoATransferir $ConexionDestino
scp $ArchivoATransferir $ConexionDestino 
}
PreparandoArchivosQt3()
{
  CopiandoQt3 
  EmpaquetaArchivosQt3
}
InstalandoEnCliente()
{
	if [ "$(VerificandoParametrosInstalacion $*)" == "1" ]
	then
		CreandoDirectorioInstalacion $(ObtenDirInstalacion $*)
	else
		ModoUsoInstalacion $*
	fi
}
EliminandoInstalacion()
{
if [ "$(EstaEliminaInstalacion $*)" == "1" ]
then
	printf "Eliminando ...\n"
fi
}
CreandoLosDirectoriosEnElCliente()
{
 ssh $(ObtenUsuario $*)@$(ObtenDirIp $*) bin/ClienteSiscomElectronica \
 	 -Instalando -DirInstalacion $(ObtenDirInstalacion $*)
}
TransfiriendoVersionSiscomElectronica()
{

if [ $(EstaUsaEsteArchivo $*) == 1 ]
then

SCPVersionSiscomElectronica -64.Bits 			\
			    -DirIp $(ObtenDirIp $*) 	\
			    -Usuario $(ObtenUsuario $*)	\
			    -UsaEsteArchivo $(ObtenUsaEsteArchivo $*)


else

SCPVersionSiscomElectronica -64.Bits 			\
			    -DirIp $(ObtenDirIp $*) 	\
			    -Usuario $(ObtenUsuario $*)
fi

}
CorreInstalacionCliente()
{
	PreparandoArchivosQt3
	CreandoLosDirectoriosEnElCliente $*
	TransfiriendoArchivosQt3 $*
	TransfiriendoVersionSiscomElectronica $*
 	CorriendoInstalacionQt3 $*		
}
EnviandoInstalacion()
{
	CorreInstalacionCliente $*
}
DescomprimiendoQt3()
{
DirInstalacionX=$(ObtenDirInstalacion $*)
   xzcat $DirInstalacionX/ArchivosQt3.tar.xz | 	\
   tar xvf - -C $DirInstalacionX/BibliotecasQt3.3.8
}
CorriendoInstalacionQt3()
{
 ssh $(ObtenUsuario $*)@$(ObtenDirIp $*) bin/ClienteSiscomElectronica \
 	 -InstalandoQt3 -DirInstalacion $(ObtenDirInstalacion $*)
}
CreandoEnlacesSimbolicosQt3()
{
DirectorioX=$(ObtenDirInstalacion $*)
(cd $DirectorioX/BibliotecasQt3.3.8 ; 
 ln -fs libqt-mt.so.3.3.8 libqt-mt.so.3 ;
 ln -fs libqui.so.1.0.0 libqui.so.1)
}
InstalandoQt3()
{
  DescomprimiendoQt3 $*
  CreandoEnlacesSimbolicosQt3 $*
}
InstalandoSiscomElectronica()
{
 UltimoArchivoS=$(BuscaUltimoArchivo ~ SiscomElectronica_* )
 printf "Instalando %s en %s \n" $UltimoArchivoS $(ObtenDirInstalacion $*)
 xzcat $UltimoArchivoS |tar xf - -C $(ObtenDirInstalacion $*)/
}
CreandoEnlacesSoporteSiscomElectronica4()
{
DirectorioX=$(ObtenDirInstalacion $*)
VersionSiscom=$(basename $UltimoArchivoS .64.Bits.tar.xz) 
EnlaceSoporte4=$DirectorioX/64.Bits/$VersionSiscom/Cliente
(cd $DirectorioX  ;								    \
 ln -s 64.Bits/$VersionSiscom SiscomElectronica.Liberacion;			    \
 cd SoporteSiscomElectronica4;					    			\
 ln -s $EnlaceSoporte4/libSiscomDesarrollo4++.so.1.0.0 libSiscomDesarrollo4++.so.1; 	\
 ln -s $EnlaceSoporte4/libSiscomComunicaciones++.so.1.0.0 libSiscomComunicaciones++.so.1;\
 ln -s $EnlaceSoporte4/libSiscomDesarrollo4Qt++.so.1.0.0 libSiscomDesarrollo4Qt++.so.1; \
 ln -s $EnlaceSoporte4/libSiscomSoporte.so.1.0.0 libSiscomSoporte.so.1 )
}
ModoUso()
{
cat << Usando |more

Hola hola hola 

Usando

}
if [ $# == 0 ]
then

  ModoUso $* 

else

DirectorioPasando=$(ObtenDirectorioPasando $*)

if [ "$(EstaEnviaInstalacion $*)" == "1" ]
then 
	EnviandoInstalacion $*
fi

##  ClienteSiscomElectronica -EnviaInstalacion -DirIp 10.8.1.91 -DirInstalacion SiscomElectronica -Usuario hgarduno \
#  -DirectorioPasando 

if [ "$(EstaInstalandoQt3 $*)" == "1" ] ## Cambiar a InstalandoSiscom o algo asi
then 
    printf "Instalando el Qt3 \n"

    InstalandoQt3 $*
    InstalandoSiscomElectronica $*
    CreandoEnlacesSoporteSiscomElectronica4 $*
    SiscomElectronicaCliente $*
    ArchivoComunicacionServidor $*
    ArchivoConfiguracionInterfaz $*
fi

if [ "$(EstaInstalando $*)" == "1" ]
then
	InstalandoEnCliente $*	
fi

fi
