#!/bin/sh 

Cliente()
{
ArchivosCliente="$1/Cliente/SISCOMTiendas3					\
$1/Configuracion/SiscomElectronica3.xml						\
$1/SiscomElectronica3/SO/libPantallasSiscomElectronica3.so			\
$1/Cliente/SO/libActualizaInventario.so 					\
$1/Cliente/SO/libAvisoNoAlcanza.so 						\
$1/Cliente/SO/libCNSClientes.so 						\
$1/Cliente/SO/libCapturaContacto.so 						\
$1/Cliente/SO/libCapturaDato.so 						\
$1/Cliente/SO/libCapturaIva.so 							\
$1/Cliente/SO/libCapturaNoCotizacion.so 					\
$1/Cliente/SO/libCapturaRangoFechas.so 						\
$1/Cliente/SO/libCapturaTelefono.so 						\
$1/Cliente/SO/libClientes.so 							\
$1/Cliente/SO/libCompras.so 							\
$1/Cliente/SO/libContDeLasPracticas.so 						\
$1/Cliente/SO/libContEscuelas.so 						\
$1/Cliente/SO/libContMaterias.so 						\
$1/Cliente/SO/libContPracticas.so 						\
$1/Cliente/SO/libCotizaDispositivos.so 						\
$1/Cliente/SO/libCotizaPractica.so 						\
$1/Cliente/SO/libCtrExistencias.so 						\
$1/Cliente/SO/libCtrExistenciasMinimas.so 					\
$1/Cliente/SO/libCtrExpendios.so 						\
$1/Cliente/SO/libDatosClienteF.so 						\
$1/Cliente/SO/libEjecutaInventario.so 						\
$1/Cliente/SO/libEmpleadosExpendio.so 						\
$1/Cliente/SO/libEstadoInventario.so 						\
$1/Cliente/SO/libExtNoAlcanzan.so 						\
$1/Cliente/SO/libFacturacion.so 						\
$1/Cliente/SO/libFacturando.so 							\
$1/Cliente/SO/libFamilias.so 							\
$1/Cliente/SO/libFirmaTiendas.so 						\
$1/Cliente/SO/libFirmateExpendio.so 						\
$1/Cliente/SO/libInventario.so 							\
$1/Cliente/SO/libManejadorPrecios.so 						\
$1/Cliente/SO/libManejadorProductos.so 						\
$1/Cliente/SO/libManejadorProveedores.so 					\
$1/Cliente/SO/libMantenProductos.so 						\
$1/Cliente/SO/libMaterialAExpendio.so 						\
$1/Cliente/SO/libMaterialPractica.so 						\
$1/Cliente/SO/libOpcionCerrar.so 						\
$1/Cliente/SO/libOrdenCompra.so 						\
$1/Cliente/SO/libOrdenElectronica.so 						\
$1/Cliente/SO/libOrdenesPorFecha.so 						\
$1/Cliente/SO/libOrdenesVendidas.so 						\
$1/Cliente/SO/libPantallasSiscomElectronica2009.so 				\
$1/Cliente/SO/libProdSimilares.so 						\
$1/Cliente/SO/libProductoPractica.so 						\
$1/Cliente/SO/libProductosInventariar.so 					\
$1/Cliente/SO/libProgramaInventario.so 						\
$1/Cliente/SO/libRangoPorcentaje.so 						\
$1/Cliente/SO/libRegistroEmpleados.so 						\
$1/Cliente/SO/libReportesVentas.so 						\
$1/Cliente/SO/libSISCOMTiendas3.so 						\
$1/Cliente/SO/libSelExpendios.so 						\
$1/Cliente/SO/libSelOrden.so 							\
$1/Cliente/SO/libSiscomElectronicaComun.so 					\
$1/Cliente/SO/libVentasElectronica.so"

ArchivosSiscomDesarrollo2="$DIRDesarrolloHGE/SISCOMDesarrollo2/libSISCOMComunControlesDesarrollo2.so 	\
$DIRDesarrolloHGE/SISCOMDesarrollo2/libSepomexCliente.so 						\
$DIRDesarrolloHGE/SISCOMDesarrollo2/libSiscomComunicaciones++.so 					\
$DIRDesarrolloHGE/SISCOMDesarrollo2/libSiscomDesarrollo2.so 						\
$DIRDesarrolloHGE/SISCOMDesarrollo2/libSiscomDesarrollo3Qt++.so 					\
$DIRDesarrolloHGE/SISCOMDesarrollo2/libSiscomFirmateSistema.so 						\
$DIRDesarrolloHGE/SISCOMDesarrollo2/libSiscomSeguridad3Prot2.so"

ArchivosQt=" 								\
$QTDIR/plugins/designer/libControlEscuelas.so 				\
$QTDIR/plugins/designer/libControlFechaDesarrollo2.so 			\
$QTDIR/plugins/designer/libControlSepomexComunicas.so 			\
$QTDIR/plugins/designer/libControlSiscomElectronica3.so 		\
$QTDIR/plugins/designer/libQCtrlServidoresSiscom.so 			\
$QTDIR/plugins/designer/libQCtrlUsuarios.so 				\
$QTDIR/plugins/designer/libQSiscomOperacionesPersonas.so 		\
$QTDIR/plugins/designer/libQSiscomSepomex++.so 				\
$QTDIR/plugins/designer/libSISCOMComunControles.so	" 

for X in $ArchivosCliente 		\
         $ArchivosSiscomDesarrollo2	\
	 $ArchivosQt
do  
cp $X $2/Cliente; 
done 

#cp $QTDIR/lib/libqt-mt.* $1/Cliente

cat << SiscomTiendas > $2/SISCOMTiendas.sh 

#!/bin/sh 

DirSistema=$1/Cliente
LD_LIBRARY_PATH=$1/Cliente

PATH=$1/Cliente
DirectorioConfiguracion=$2/Cliente/
ArchivoConfiguracionModulos=SiscomElectronica3.xml
Aplicacion=SISCOMElectronica
RutaIconos=$HOME/.SiscomElectronica/Cliente/Iconos
ArchivoServidores=.SiscomTiendasComunicaciones3.txt


IdCaja=

export LD_LIBRARY_PATH
export PATH
export DirectorioConfiguracion
export ArchivoConfiguracionModulos
export Aplicacion
export PtoComSvr2 
export RutaIconos
export ArchivoServidores 

export IdExpendio
export DirIpSvr
export PtoComSvr
export IdCaja
ulimit -c 0

SISCOMTiendas3 Maximizada

SiscomTiendas

chmod +x $2/SISCOMTiendas.sh

}
Servidor()
{
ArchivosServidor="							\
$1/Servidor/libSiscomElectronica.so 					\
$1/Servidor/libSiscomElectronicaMemoriaComun.so				\
$DIRLIBSISCOM2/libSiscomAplicacionesSvr.so 				\
$DIRLIBSISCOM2/libSiscomDesarrollo2.so 					\
$DIRLIBSISCOM2/libSiscomDesarrolloPostgresql.so 			\
$DIRLIBSISCOM2/libSiscomSeguridad3Prot2.so 				\
$DIRLIBSISCOM2/libSiscomSepomex.so 					\
$DIRLIBSISCOM2/Servidor/ServidorGeneral					\
$DIRDesarrolloHGE/ActualizaAplicacion/Servidor/libAccesoDatos.so	\
$1/SiscomElectronica2/Servidor/libSiscomElectronica2.so"

for X in $ArchivosServidor
do
cp $X $2/Servidor 
done
}






## Miercoles 25 Noviembre del 2014 
##Se integro la generacion del archivo tar.zx 
## Viernes 31 de Julio del 2015, no se explica 
## como se pasa el nombre o ruta de directorios

lchrArrRuta=`
awk '
function BuscaPlataforma(pchrPtrCamposRuta)
{
 lchrArrRutaBase="";
  for(lintContador=2; ;lintContador++)
  {
	if(index(pchrPtrCamposRuta[lintContador],"Bits"))
	{
	  break;
	}
	else
	{
	   lchrArrRutaBase=lchrArrRutaBase "/" (lchrArrRutaBase = pchrPtrCamposRuta[lintContador])
	}

  }

return lchrArrRutaBase;
}


BEGIN {

 Directorio="'"$1"'"

 lintRegreso=split(Directorio,lchrArrSalida,"/");
 lchrArrRutaBase=BuscaPlataforma(lchrArrSalida);
 printf("%s",lchrArrRutaBase);

 
}'` 
lchrArrNombreArchivo=`
awk ' 
function GeneraNombreArchivo(pchrPtrCamposRuta,pintUltimo)
{
for(lintContador=2; ;lintContador++)
  {
	if(index(pchrPtrCamposRuta[lintContador],"Bits"))
	{
	  
	  break;
	}

  }
lchrArrNombre=pchrPtrCamposRuta[pintUltimo] "." (lchrArrNombre = pchrPtrCamposRuta[lintContador]);
printf("%s",lchrArrNombre);
}
BEGIN{
	lintRegreso=split("'"$1"'",lchrArrCamposRuta,"/");
	GeneraNombreArchivo(lchrArrCamposRuta,lintRegreso);

}'`

lchrArrRutaVersion=`awk ' 

function GeneraRutaVersion(pchrPtrCamposRuta,pintNCampos)
{
	lchrArrRutaVersion=".";
	for(lintContador=2;;lintContador++)
	{
	   if(index(pchrPtrCamposRuta[lintContador],"Bits"))
	   break;
	}
	for(lintContadorI=lintContador;lintContadorI<=pintNCampos;lintContadorI++)
	   lchrArrRutaVersion=lchrArrRutaVersion "/" (lchrArrRutaVersion = pchrPtrCamposRuta[lintContadorI]);

printf("%s",lchrArrRutaVersion);
}
BEGIN{

	lintRegreso=split("'"$1"'",lchrArrCamposRuta,"/");
	GeneraRutaVersion(lchrArrCamposRuta,lintRegreso);

}'`


NombrePorFecha()
{
#Enero
#Febrero
#Marzo
#Abril
#Mayo
#Junio
#Julio
#Agosto
#Septiembre
#Octubre
#Noviembre
#Diciembre

Dia=`date '+%A'|  sed -e s/^l/L/ -e s/^m/M/ -e s/^j/J/ -e s/^v/V/ -e s/^s/S/ -e s/?/e/g `
	Mes=`date '+%B'|  sed -e s/^e/E/ -e s/^f/F/ -e s/^a/A/ -e s/^m/M/ -e s/^j/J/ -e s/^s/S/ -e s/^o/O/ -e s/^n/N/ -e s/^d/D/ `
NDia=`date '+%d'`
Anio=`date '+%Y'`
printf "SiscomElectronica_%s_%s_%s_%s_%s\n" $Dia $NDia $Mes $Anio $Procesador
}


CreaDirectoriosParaInstalar()
{
Rutas=$(awk  'BEGIN{
	lintInicio=0;
	lintRegresoRutaSalida=split("'"$2"'",lchrArrCamposRutaSalida,"/");
	lintRegresoRutaBase=split("'"$1"'",lchrArrCamposRutaBase,"/");
	for(lintContador=lintRegresoRutaBase+1; lintContador<=lintRegresoRutaSalida; lintContador++)
	{
	   if(lintInicio==0)
	   lchrArrPrimerNivel=sprintf("%s/%s","'"$1"'",lchrArrCamposRutaSalida[lintContador]);
	   else
	   {
	    lchrArrPrimerNivel=sprintf("%s/%s",lchrArrPrimerNivel,lchrArrCamposRutaSalida[lintContador]);
	   }
	   printf("%s ",lchrArrPrimerNivel);
	   lintInicio++;
	}
	}')


for X in $Rutas
do
if [ -d $X ]
then
	rm -rf $X/*
else
	mkdir $X	
fi
done
}
CreaDirectoriosParaInstalar $lchrArrRuta  $1

if [ -d $1 ]
then
   echo 'Creando Version Siscom Electronica'
   rm -rf $1
   mkdir $1
fi


if [ -d $1/Cliente  ]
then
	rm -rf $1/Cliente
else
	mkdir $1/Cliente
fi

if [ -d $1/Servidor ]
then 
	rm -rf $1/Servidor
else
	mkdir $1/Servidor 
fi


#echo $lchrArrRuta/`NombrePorFecha`$lchrArrNombreArchivo.tar.xz
### Miercoles 1 de Julio del 2015 
# Si se pasa en la ruta al final / se vuelve loco el script
Cliente $DIRDesarrolloHGE/SISCOMElectronica $1
Servidor $DIRDesarrolloHGE/SISCOMElectronica $1
#echo $lchrArrRuta $lchrArrNombreArchivo
#if [ -f $lchrArrRuta/$lchrArrNombreArchivo.tar.xz ]
#then
# rm $lchrArrRuta/$lchrArrNombreArchivo.tar.xz 
#fi
#(cd  $lchrArrRuta ; 					\
# echo 'Creando el tar ' ; 				\
# tar cf $lchrArrNombreArchivo.tar $lchrArrRutaVersion ; \
# echo Comprimiendo ; xz -z  $lchrArrNombreArchivo.tar)
