#!/bin/bash 

source ~/bin/FuncionesComunesBash 

DirectorioPostgres=/home/postgres/Versiones/17.2.0

EstaBaseMatriz()
{
OpcionABuscar=BaseMatriz
echo $(EstaLaOpcion $*)
}

EstaNombre()
{
OpcionABuscar=Nombre
echo $(EstaLaOpcion $*)
}


EstaIdBodega()
{

OpcionABuscar=IdBodega
echo $(EstaLaOpcion $*)
}

EstaDirIpExpendio()
{
OpcionABuscar=DirIpExpendio
echo $(EstaLaOpcion $*)


}
EstaBaseExpendio()
{
OpcionABuscar=BaseExpendio
echo $(EstaLaOpcion $*)
}
EstaRegistroExpendio()
{
OpcionABuscar=RegistroExpendio
echo $(EstaLaOpcion $*)
}
EstaRegistroBodegaMatriz()
{
OpcionABuscar=RegistroBodegaMatriz
echo $(EstaLaOpcion $*)
}
EstaRegistroBodegaMatrizMatriz()
{
OpcionABuscar=RegistroBodegaMatrizMatriz
echo $(EstaLaOpcion $*)
}
EstaIdExpendio()
{
OpcionABuscar=IdExpendio
echo $(EstaLaOpcion $*)
}
EstaEliminaBodegaExpendio()
{
OpcionABuscar=EliminaBodegaExpendio
echo $(EstaLaOpcion $*)
}
ObtenIdExpendio()
{
Parametro=IdExpendio
echo $(ObtenParametroEntrada $*)
}
ObtenIdBodega()
{
Parametro=IdBodega
echo $(ObtenParametroEntrada $*)
}
ObtenNombre()
{
Parametro=Nombre
echo $(ObtenParametroEntrada $*)
}
ObtenDirIpExpendio()
{
Parametro=DirIpExpendio
echo $(ObtenParametroEntrada $*)
}
ObtenUsuario()
{

Parametro=Usuario
echo $(ObtenParametroEntrada $*)

}
ObtenBaseExpendio()
{
Parametro=BaseExpendio
echo $(ObtenParametroEntrada $*) 
}
ObtenBaseMatriz()
{
Parametro=BaseMatriz
echo $(ObtenParametroEntrada $*)
}
ObtenDirPostgres()
{
Parametro=DirPostgres
echo $(ObtenParametroEntrada $*)
}
OpcionesCompletasRegistroBodegaMatriz()
{

if [[ $(EstaRegistroBodegaMatriz $*) == 1 &&
      $(EstaIdBodega $*)       == 1 && 
      $(EstaNombre $*)         == 1 &&
      $(EstaBaseMatriz $*)     == 1 ]]
then
	echo 1
else
	echo 0
fi
}
OpcionesCompletasEliminaBodegaExpendio()
{
 if [[ $(EstaEliminaBodegaExpendio $*) == 1 &&
      $(EstaIdBodega $*)	      == 1  &&
      $(EstaBaseMatriz $*)           == 1 ]]
  then 
  	echo 1 
  else
  	echo 0
  fi
}
ModoUsoRegistroBodegaMatriz()
{
cat << ModoUso |more

RegistraBodega , es un script que permite registrar en la matriz y en el expendio
remoto una nueva bodega

Modo de Uso


RegistraBodega  -RegistroBodegaMatrizMatriz 	#Se le indica para realizar el registro de la
				 	#bodega en matriz
		
		-IdBodega 		#Identificador consecutivo de la bodega

		-Nombre   		#Nombre de la bodega, no se pueden usar espacios 
			  		#en lugar de espacio se pude poner un guion bajo
					
		-BaseMatriz 	 	#Nombre de la base de datos en la matriz
		-IdMatriz 

Se pasan estas opciones para registrar en la matriz los datos de la bodega que sera
		-IdExpendio 
		-DirIpExpendio 

Las opciones anteriores son necesarias para realizar el registro de la bodega en la matriz.

Ademas se deben agregar las siguientes opciones, para realizar el registro en el expendio

		-Usuario              
		-DirIpExpendio         #Direccion Ip del expendio 
		-BaseExpendio	       #Base de datos del expendio

Comando para eliminar una bodega de la base de datos de la matriz 

RegistroBodegaMatriz -EliminaBodegaExpendio 
			-IdBodega 
			-BaseMatriz  

Ejemplo para registrar la Bodega con Id 200, nombre Bodega_Expendio_200 , 
	en la base de la matriz SiscomElectronica, en el expendio con direccion ip 
	127.0.0.0 , el usuario hgarduno la base del expendio Expendio_200

RegistraBodega -RegistroBodegaMatriz 			
		-IdBodega 200 
		-Nombre Bodega_Expendio_200 
		-BaseMatriz SiscomElectronica 
		-DirIpExpendio 127.0.0.1 
		-IdExpendio 200  
		-BaseExpendio Expendio_200 
		-Usuario hgarduno

ModoUso

}
####### Argumentos 
##### IdBodega
##### Nombre 
##### Base de datos 
##### IdExpendio (Puede ser la Matriz )
RegistraBodegaMatriz()
{
echo $*
cat << RegMatriz  | $DirectorioPostgres/bin/psql $3
insert into Bodegas values($1,'$2');

insert into bodegaexpendio values($4,$1);
RegMatriz


}

OpcionesCompletasRegistroExpendio()
{
 if [ $(EstaRegistroExpendio $*) == 1 ]
 then
 	echo 1
  else
  	echo 0
fi
}
#### Argumentos
## IdBodega 
## Base Expendio
RegistraBodegaEnElExpendio()
{
cat << BodegaEnElExpendio  | $DirectorioPostgres/bin/psql $2
insert into Bodegas values($1,'$3');
insert into materialbodega select $1,
	           cveproducto,
		   0,
		   0
	    from productos 
BodegaEnElExpendio
}
###### Argumentos 
# Usuario 
# DirIpExpendio
# IdBodega
# Nombre
# Base Expendio

RegistrandoEnElExpendio()
{
ssh $1@$2 ~/bin/RegistraBodega 	-RegistroExpendio 				\
			     	-IdBodega $3 					\
				-Nombre $4					\
				-BaseExpendio $5				\
				-IdExpendio $6
					
}

ObtenIdMatriz()
{
echo 'select idempresa from matriz' |psql $1 -tA

}
# Revisar para ejecutar en el expendio remoto 
# $1 IdBodega 
# $2 Base de datos 
#
# Solo para eliminar la bodega de la matriz , en esta fase de 
# pruebas , se debera integrar la funcionalidad para eliminar 
# la bodega del expendio tambien :)
#
EliminaBodegaExpendio()
{
cat << BorraBodega | $DirectorioPostgres/bin/psql $2
delete from transferenciabodegabodega where idbodegaorigen=$1;
delete from transferenciabodegabodega where idbodegadestino=$1;
delete from inventariobodega where idbodega=$1;
delete from materialbodega where idbodega=$1;
delete from bodegaexpendio where idbodega=$1;
delete from bodegas where idbodega=$1;
BorraBodega
}

if [ $(OpcionesCompletasRegistroBodegaMatriz $*) == 1 ]
then
      RegistraBodegaMatriz $(ObtenIdBodega $*) 		\
      			   $(ObtenNombre $*) 		\
			   $(ObtenBaseMatriz $*) 	\
			   -$(ObtenIdExpendio $*) 

         RegistrandoEnElExpendio $(ObtenUsuario $*)  		\
	 			 $(ObtenDirIpExpendio $*) 	\
				 $(ObtenIdBodega $*)		\
				 $(ObtenNombre $*)		\
				 $(ObtenBaseExpendio $*)	\
				 $(ObtenIdExpendio $*)
else
if [ $(OpcionesCompletasRegistroExpendio $*) == 1 ]
then
	printf "Ahora registro en el expendio \n"
	RegistraBodegaEnElExpendio $(ObtenIdBodega $*) 		\
				   $(ObtenBaseExpendio $*)	\
				   $(ObtenNombre $*)
else
if [ $(OpcionesCompletasEliminaBodegaExpendio $*) == 1  ]
then
	EliminaBodegaExpendio $(ObtenIdBodega $*) 	\
			      $(ObtenBaseMatriz $*)
fi
fi
fi

