

Archivos_SiscomElectronica=O/SiscomElectronica.o 			\
			   O/RNVentasElectronica.o 			\
			   O/RNPersonas.o  				\
			   O/RNProductos.o 				\
			   O/RNCotizaDispositivos.o 			\
			   O/RNEscuelas.o 				\
			   O/RNMaterias.o 				\
			   O/RNPracticas.o 				\
			   O/RNEmpresas.o 				\
			   O/RNEmpleadosExpendio.o 			\
			   O/RNValidaFirma.o  				\
			   O/RNDatosClienteF.o 				\
			   O/RNInventario.o  				\
			   O/RNCompras.o  				\
			   O/RNFamilias.o 				\
			   O/RNUnidades.o 				\
			   O/RNReportesVentas.o 			\
			   O/RNTipoPrecios.o 				\
			   O/RNTransfiereProductos.o 			\
			   O/ComunElectronica.o  			\
			   O/RNIniciaExpendio.o				\
			   O/VentasPorHora.o				\
			   O/ControladorOrdenes.o 			\
			   O/OrdenCompra.o				\
			   O/SiscomElectronica4.o			\
			   O/SistemaPedidos.o				\
			   O/ProductosSE.o				\
			   O/EscuelasSE.o				\
			   O/Cotizando4.o				\
			   O/ComunSiscomElectronica4.o			\
			   O/OrdenesVendidas.o				\
			   O/Facturando4.o				\
			   O/ExistenciaExpendios.o			\
			   O/Clientes4.o				\
			   O/ImpresionTicketVenta.o			\
			   O/TicketPedido.o				\
			   O/RegistraOrden.o				\
			   O/Practicas.o				\
			   O/ReportesSiscom.o				\
			   O/TransferenciasExpendioAExpendio.o		\
			   O/ImpresionTransferencias.o			\
			   O/CircuitosImpresos.o			\
			   O/ClavesSatSiscom.o				\
			   O/GastosExpendio.o				\
			   O/PedidosExpendio.o				\
			   O/Proveedores4.o				\
			   O/PesoProducto.o				\
			   O/CompraImportacion.o			\
			   O/OrdenRapida.o				\
			   O/RegistraUsuario.o				\
			   O/ProductosSiscom.o				\
			   O/Seguridad3.o				\
			   O/Precios.o					\
			   O/CotizacionImportacion.o			\
			   O/Empresas.o					\
			   O/CatalogosSat.o				\
			   O/Devoluciones4.o				\
			   O/OrdenCompraImportacion.o			\
			   O/ClavesProveedor.o				\
			   O/UbicacionMaterial.o			\
			   O/OrdenesFavoritas.o				\
			   O/CorteCaja.o				\
			   O/PuntosEntrega.o				\
			   O/OperacionesPedidos.o			\
			   O/JTExpress.o				\
			   O/PedidosCliente.o				\
			   O/Contenedor.o				\
			   O/SincronizaExpendios.o			\
			   O/TiendaLinea.o				\
			   O/SoporteTiendaLinea.o			\
			   O/PdfFactura.o				\
			   O/Bodegas4.o					\
			   O/FormaPago.o				\
			   O/AbonoAApartado.o				\
			   O/ComprasSiscom.o				\
			   O/SqlSiscomElectronica.o			\
			   O/SqlValidandoTransferencias.o		\
			   O/SqlCotizaDispositivos.o			\
			   O/SqlCompras.o				\
			   O/SqlSistemaPedidos.o			\
			   O/SqlProductosSE.o				\
			   O/SqlEscuelasSE.o				\
			   O/SqlCotizando4.o				\
			   O/SqlOrdenesVendidas.o			\
			   O/SqlClientes4.o				\
			   O/SqlExistenciaExpendios.o			\
			   O/SqlImpresionTicketVenta.o			\
			   O/SqlOrdenes.o				\
			   O/SqlPracticas.o				\
			   O/SqlReportesSiscom.o			\
			   O/SqlTransferenciasExpendioAExpendio.o	\
			   O/SqlCircuitoImpreso.o			\
			   O/SqlClavesSatSiscom.o			\
			   O/SqlGastosExpendio.o			\
			   O/SqlPedidosExpendio.o			\
			   O/SqlProveedores4.o				\
			   O/SqlPesoProducto.o				\
			   O/SqlCompraImportacion.o			\
			   O/SqlOrdenRapida.o				\
			   O/SqlProductosSiscom.o			\
			   O/SqlRegistraUsuario.o			\
			   O/SqlSeguridad3.o				\
			   O/SqlPrecios.o				\
			   O/SqlCotizacionImportacion.o			\
			   O/SqlEmpresas.o				\
			   O/SqlCatalogosSat.o				\
			   O/SqlDevoluciones.o				\
			   O/SqlClavesProveedor.o			\
			   O/SqlOrdenCompraImportacion.o		\
			   O/SqlUbicacionMaterial.o			\
			   O/SqlOrdenesFavoritas.o			\
			   O/SqlPuntosEntrega.o				\
			   O/SqlJTExpress.o				\
			   O/SqlPedidosCliente.o			\
			   O/SqlSincronizaExpendios.o			\
			   O/SqlTiendaLinea.o				\
			   O/SqlBodegas.o				\
			   O/SqlFormaPago.o				\
			   O/SqlCorteCajaSucursal.o			\
			   O/SqlAbonoAApartado.o			\
			   O/SqlComprasSiscom.o

			   
Archivos_SiscomElectronicaMemoriaComun=O/SiscomElectronicaMemoriaComun.o			   

Bibliotecas=-L$(DIRLIBSISCOM2)  			\
	    -L../SiscomElectronica2/Servidor		\
	    -L$(DIRDesarrolloHGE)/SiscomDesarrollo4	\
	    -L$(DirLibHaru)/lib64			\
		-lSiscomDesarrollo2  			\
		-lSiscomSeguridad3Prot2			\
		-lSiscomSepomex				\
		-lSiscomAplicacionesSvr			\
		-lSiscomElectronica2			\
		-lSiscomDesarrollo4			\
		-lSiscomOperaciones			\
		-lhpdf

BibliotecasMemoriaComun=-L$(DIRLIBSISCOM2) -lSiscomDesarrollo2 
Include=-IH 									\
	-I $(DIRDesarrolloHGE)/SISCOMDesarrollo2/H 				\
	-I$(DIRDesarrolloHGE)/SISCOMDesarrollo2/Servidor/H			\
	-I$(DirectorioSiscomElectronica)/SiscomElectronica2/Servidor/H 		\
	-I$(DirectorioSiscomElectronica)					\
	-I$(DIRDesarrolloHGE)/Sepomex/Servidor/H				\
	-I$(DIRDesarrolloHGE)/SiscomDesarrollo4/H				\
	-I$(DIRDesarrolloHGE)							\
	-I$(DirLibHaru)/include
OpC=-g -c  $(DEBUG) $(OpCSiscom)
OpShared=-g -shared $(DEBUG) $(OpCSiscom)
OpBinarios=-g  $(DEBUG) $(OpCSiscom)

Binarios= 						\
	 libSiscomElectronica.so    			\
	 libSiscomElectronicaMemoriaComun.so
	 	

all:DirectorioO $(Binarios) 


DirectorioO:
	-mkdir O

libSiscomElectronica.so:$(Archivos_SiscomElectronica) ../SiscomElectronica2/Servidor/libSiscomElectronica2.so
	@echo Generando $@
	@$(GCC) $(OpShared) -o $@ $(Archivos_SiscomElectronica) $(Bibliotecas)

libSiscomElectronicaMemoriaComun.so:$(Archivos_SiscomElectronicaMemoriaComun)
	@echo Generando $@
	@$(GCC) $(OpShared) -o $@ $(Archivos_SiscomElectronicaMemoriaComun) $(BibliotecasMemoriaComun)

O/%.o:C/%.c
	@echo Compilando $<
	@$(GCC) $(OpC) -o $@ $< $(Include) 

clean:
	-rm $(Binarios)
	-rm O/*.o
	
	
