#!/bin/sh

DirServidor=$HOME/ElFresno/ServidorProtocolo2

LD_LIBRARY_PATH=$LD_LIBARY_PATH:$DIRPOSTGRESQL/lib:$DirServidor:$DIRDesarrolloHGE/ActualizaAplicacion/Servidor:$DIRLIBSISCOM2
PATH=$PATH:$DIRDesarrolloHGE/SISCOMDesarrollo2/Servidor
BDSeguridad3=ElFresno
export	LD_LIBRARY_PATH \
	PATH		\
	BDSeguridad3

start()
{

		ServidorGeneral $DirServidor/ConfiguracionSiscom.2645.ini	
		ServidorGeneral $DirServidor/ConfiguracionSiscom.2646.ini	
}
stop()
{
	for X in `find $DirServidor -name '*.pid'` 
	do
	     kill -16 `cat $X`
	     rm $X
	done	
}
case "$1" in
	start)
		start		

	;;
	stop)
		stop
	;;
	status)
		status
	;;
	restart)
		restart
	;;
	*)
	echo "Use ServidorSiscom start|stop|restart|status"
	exit 1
esac
