#!/bin/sh
LD_LIBRARY_PATH=$QTDIR/lib:$SISCOM_LIB_DIR:Cliente/SO:$DIRLIBSISCOM2

PATH=Cliente/B
RutaIconosSiscomSeguridad3=/KDE/share/icons/hicolor/48x48/apps/

export 	LD_LIBRARY_PATH		\
	PATH			\
	RutaIconosSiscomSeguridad3


/usr/bin/gdb $DIRDesarrolloHGE/SISCOMSeguridad3/Cliente/B/SistemaDeSeguridad3
#$DIRDesarrolloHGE/SISCOMSeguridad3/Cliente/B/SistemaDeSeguridad3
