insert into Estatus values(1,'A','Activo');
insert into Estatus values(2,'I','Inactivo');
insert into Estatus values(3,'D','Descontinuado');
insert into Estatus values(4,'V','Vendido');
insert into Estatus values(5,'P','Apartado');
insert into Estatus values(6,'E','Devuelto');
insert into Estatus values(7,'B','Baja');
insert into Estatus values(8,'N','Danado');
insert into Estatus values(9,'L','Liquidacion');
